CREATE TABLE `owner_login_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerAccountId` int NOT NULL,
	`template` varchar(40) NOT NULL DEFAULT 'professional',
	`backgroundStyle` varchar(40) NOT NULL DEFAULT 'gradient',
	`backgroundColor` varchar(32) NOT NULL DEFAULT '#f4f7ff',
	`backgroundGradient` varchar(600),
	`backgroundImageUrl` longtext,
	`backgroundImageMediaId` bigint,
	`logoUrl` longtext,
	`logoMediaId` bigint,
	`logoSize` int NOT NULL DEFAULT 64,
	`logoPosition` varchar(32) NOT NULL DEFAULT 'top',
	`logoShape` varchar(32) NOT NULL DEFAULT 'rounded',
	`logoBorderColor` varchar(32) NOT NULL DEFAULT '#ffffff',
	`logoBorderWidth` int NOT NULL DEFAULT 0,
	`logoGlow` int NOT NULL DEFAULT 0,
	`logoAnimation` varchar(32) NOT NULL DEFAULT 'none',
	`ownerPhotoUrl` longtext,
	`ownerPhotoMediaId` bigint,
	`ownerPhotoSize` int NOT NULL DEFAULT 0,
	`ownerPhotoShape` varchar(32) NOT NULL DEFAULT 'circle',
	`cardStyle` varchar(40) NOT NULL DEFAULT 'standard',
	`cardColor` varchar(32) NOT NULL DEFAULT '#ffffff',
	`cardOpacity` int NOT NULL DEFAULT 94,
	`cardBorderColor` varchar(32) NOT NULL DEFAULT '#ffffff',
	`cardBorderWidth` int NOT NULL DEFAULT 1,
	`cardRadius` int NOT NULL DEFAULT 28,
	`cardBlur` int NOT NULL DEFAULT 0,
	`cardWidth` int NOT NULL DEFAULT 430,
	`fieldStyle` varchar(32) NOT NULL DEFAULT 'modern',
	`fieldColor` varchar(32) NOT NULL DEFAULT '#ffffff',
	`fieldTextColor` varchar(32) NOT NULL DEFAULT '#15213d',
	`fieldPlaceholderColor` varchar(32) NOT NULL DEFAULT '#77829a',
	`fieldBorderColor` varchar(32) NOT NULL DEFAULT '#dce2f1',
	`fieldBorderWidth` int NOT NULL DEFAULT 1,
	`fieldRadius` int NOT NULL DEFAULT 14,
	`fieldFontSize` int NOT NULL DEFAULT 15,
	`buttonStyle` varchar(32) NOT NULL DEFAULT 'gradient',
	`buttonColor` varchar(32) NOT NULL DEFAULT '#4966d6',
	`buttonTextColor` varchar(32) NOT NULL DEFAULT '#ffffff',
	`buttonRadius` int NOT NULL DEFAULT 14,
	`buttonGlow` int NOT NULL DEFAULT 0,
	`buttonAnimation` varchar(32) NOT NULL DEFAULT 'none',
	`entranceAnimation` varchar(32) NOT NULL DEFAULT 'fade',
	`animationDuration` int NOT NULL DEFAULT 240,
	`title` varchar(320) NOT NULL DEFAULT 'مرحبًا بك في لوحة الإدارة',
	`description` longtext NOT NULL,
	`loginButtonText` varchar(120) NOT NULL DEFAULT 'تسجيل الدخول',
	`passkeyButtonText` varchar(160) NOT NULL DEFAULT 'تسجيل الدخول بالبصمة أو Passkey',
	`footerText` varchar(500) NOT NULL DEFAULT 'دخول خاص ومؤمّن لإدارة الموقع وطلبات العملاء.',
	`invalidCredentialsText` varchar(300) NOT NULL DEFAULT 'بيانات الدخول غير صحيحة',
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `owner_login_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `owner_login_settings_owner_unique` UNIQUE(`ownerAccountId`)
);
--> statement-breakpoint
CREATE TABLE `owner_passkeys` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`ownerAccountId` int NOT NULL,
	`credentialId` varchar(1024) NOT NULL,
	`publicKey` longtext NOT NULL,
	`counter` bigint NOT NULL DEFAULT 0,
	`transports` varchar(500),
	`label` varchar(120) NOT NULL,
	`lastUsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `owner_passkeys_id` PRIMARY KEY(`id`),
	CONSTRAINT `owner_passkeys_credential_unique` UNIQUE(`credentialId`)
);
--> statement-breakpoint
CREATE TABLE `owner_webauthn_challenges` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`ownerAccountId` int,
	`challenge` varchar(1024) NOT NULL,
	`ceremony` enum('registration','authentication') NOT NULL,
	`origin` varchar(500) NOT NULL,
	`rpId` varchar(255) NOT NULL,
	`expiresAt` timestamp NOT NULL,
	`usedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `owner_webauthn_challenges_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `owner_passkeys_owner_index` ON `owner_passkeys` (`ownerAccountId`);--> statement-breakpoint
CREATE INDEX `owner_webauthn_challenges_lookup_index` ON `owner_webauthn_challenges` (`challenge`,`ceremony`,`usedAt`);